### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by charlesthobe**
This is mostly to see what's up with the bot not starting in https://github.com/flathub/net.mancubus.SLADE/pull/58
Merging this will presumably mark the other PR as accepted since when https://github.com/flathub/net.mancubus.SLADE/pull/57 got merged https://github.com/flathub/net.mancubus.SLADE/pull/56 got marked as merged along with it.

### CODE REVIEW

**Comment by charlesthobe** [comment]
Bot fail, trying commit amending.

**Comment by charlesthobe** [comment]
Same BS

**Comment by charlesthobe** [comment]
Trying again in a couple of hours.

**Comment by Eonfge** [comment]
Thanks for your contribution

**Pull request merged**
