### PR TITLE
Update ACS Compiler

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Review by Calinou — APPROVED** [review]

**Comment by Eonfge** [comment]
Bot, build

**Comment by Eonfge** [comment]
Bot, build

**Comment by charlesthobe** [comment]
I think you could clone the repo locally then `git commit --amend` then force push to kick the bot.
Not 100% sure if that would work though.

**Comment by charlesthobe** [comment]
what `git commit --amed` is change the commit time stamp even if the authoring time stamp is not changed.

**Pull request merged**
