### PR TITLE
Update runtime and fix build

### PR DESCRIPTION
**Pull request by charlesthobe**

### CODE REVIEW

**Comment by charlesthobe** [comment]
While building SLADE wx spits out deprecation warnings though, so I think pinning its version instead of letting the x-data-checker update it could be considered.
nonetheless version 3.1.5 had a cmake problem that prevented it from building using the 45 gnome SDK.

**Comment by charlesthobe** [comment]
The bot is asleep or something :man_facepalming:

**Comment by charlesthobe** [comment]
:man_shrugging:

**Comment by Eonfge** [comment]
Thank you so much for assisting me. The work was getting a bit too much, so your pull request is much appreciated!

**Comment by charlesthobe** [comment]
You're welcome

**Pull request merged**
