### PR TITLE
Updated SLADE to 3.1.10

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Comment by Eonfge** [comment]
For something that's supposedly a simple hotfix, a lot has changed. I'll have to look into this later.

**Comment by Eonfge** [comment]
@Calinou Any suggestions, because the system keeps consistently failing to find std:filesystem?

**Comment by Calinou** [comment]
@Eonfge As I was told on IRC:

```text
<vidal72[m]> Calinou: someone reported it before, iirc you have to link std::filesystem dynamically beacuse static libs isn't shipped
```

**Comment by Eonfge** [comment]
I reported our current workarounds upstream. Hope then can be resolved:
https://github.com/sirjuddington/SLADE/issues/1111

**Comment by Eonfge** [comment]
PEBKAC. 

@Calinou Let's make sure we double test this one, because all of this is a bad omen

**Comment by Eonfge** [comment]
@Calinou Works for me. Only issue I spotted is that the version string in the about page says _3.2.0 beta 1_, which is an error by upstream.

**Comment by Calinou** [comment]
@Eonfge I just tested it, it's working well :slightly_smiling_face: 

image

**Comment by Eonfge** [comment]
Thanks for the teamwork

**Pull request merged**
