### PR TITLE
Disable network access while FreeImage is bundled

### PR DESCRIPTION
**Pull request by Alexander-Wilms**

### CODE REVIEW

**Comment by Alexander-Wilms** [comment]
bot, build

**Comment by Alexander-Wilms** [comment]
```
Running appstreamcli compose
Saving screenshots in /srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-luGQye/files/share/app-info/media
FB: Running: appstreamcli compose --no-partial-urls --prefix=/ --origin=net.mancubus.SLADE --media-baseurl=https://dl.flathub.org/media --media-dir=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-luGQye/files/share/app-info/media --result-root=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-luGQye/files --data-dir=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-luGQye/files/share/app-info/xmls --icons-dir=/srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-luGQye/files/share/app-info/icons/flatpak '--components=net.mancubus.SLADE,net.mancubus.SLADE.desktop' /srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-luGQye/files
Only accepting components: net.mancubus.SLADE, net.mancubus.SLADE.desktop
Processing directory: /srv/buildbot/worker/build-x86_64/build/.flatpak-builder/rofiles/rofiles-luGQye/files
Composing metadata...
Run failed, some data was ignored.
Errors were raised during this compose run:
net.mancubus.SLADE
  E: icon-not-found
general
  E: filters-but-no-output
Refer to the generated issue report data for details on the individual problems.
Error: ERROR: appstreamcli compose failed: Child process exited with code 1
```

**Comment by Alexander-Wilms** [comment]
bot, build

**Comment by Eonfge** [comment]
I have no idea why that suddenly fails. I also had another project who's metadata suddenly gave trouble

**Comment by Alexander-Wilms** [comment]
Maybe the backend was switched from appstream-glib to libappstream. I'll try to fix that.

**Comment by Alexander-Wilms** [comment]
This seems tangentially related: https://github.com/flathub/flathub/issues/4222

**Comment by Alexander-Wilms** [comment]
bot, build

**Comment by Calinou** [comment]
- Superseded by https://github.com/flathub/net.mancubus.SLADE/pull/78.

**Pull request closed without merging**
